"use client";

import { useEffect, useState } from "react";
import { supabase } from "../../../lib/supabase";
import type { SettingRow } from "../../../lib/types";
import { EmptyState, LoadingState, PageHeader } from "../../../components/admin/ui";

const names: Record<string, { title: string; text: string }> = { contact_information: { title: "Contact information", text: "These contact details are used consistently across the public website, footer, contact page, and quick-contact menu." }, business_hours: { title: "Business hours", text: "Reception availability shown on the public website." }, social_links: { title: "Social media", text: "Public social media links." }, seo_defaults: { title: "Website", text: "Public KODESK website configuration." } };
const fieldLabels: Record<string, string> = { phone: "Phone number", email: "Email address", address: "Business address", whatsapp_number: "WhatsApp number", whatsapp_message: "WhatsApp prefilled message", reception: "Reception hours", site_url: "Public website URL", default_title: "Default SEO title", default_description: "Default SEO description", canonical_url: "Default canonical URL" };
const settingDefaults: Record<string, Record<string, string>> = { seo_defaults: { site_url: "", default_title: "", default_description: "", canonical_url: "" } };

export default function SettingsPage() {
  const [items, setItems] = useState<SettingRow[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState<string | null>(null); const [notice, setNotice] = useState("");
  const load = async () => { if (!supabase) return; setLoading(true); const { data, error } = await supabase.from("site_settings").select("*").order("key"); if (error) setNotice("We couldn't load settings. Please try again."); else setItems(((data ?? []) as SettingRow[]).map((item) => ({ ...item, value: { ...(settingDefaults[item.key] ?? {}), ...item.value } }))); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const edit = (id: string, field: string, value: string) => setItems((all) => all.map((item) => item.id === id ? { ...item, value: { ...item.value, [field]: value } } : item));
  const save = async (item: SettingRow) => { if (!supabase) return; if (Object.values(item.value).some((value) => typeof value === "string" && value.toLowerCase().startsWith("javascript:"))) return setNotice("Unsafe URLs are not allowed."); setSaving(item.id); const { error } = await supabase.from("site_settings").update({ value: item.value }).eq("id", item.id); setSaving(null); setNotice(error ? "Unable to save settings." : "Settings saved successfully. Public contact details will update shortly."); };
  return <><PageHeader title="Settings" subtitle="Manage the business information shown across the KODESK website"/>{notice && <div className="toast-message">{notice}</div>}{loading ? <LoadingState rows={5}/> : items.length ? <section className="settings-list">{items.map((item) => { const copy = names[item.key] ?? { title: item.key.replaceAll("_", " "), text: "Public website configuration." }; return <article className="surface settings-card" key={item.id}><div className="surface-heading"><div><h2>{copy.title}</h2><p>{copy.text}</p></div></div><div className="settings-fields">{Object.entries(item.value).map(([field, value]) => <label key={field}>{fieldLabels[field] ?? field.replaceAll("_", " ")}{field === "whatsapp_message" ? <textarea maxLength={500} value={String(value ?? "")} onChange={(event) => edit(item.id, field, event.target.value)} placeholder="Message opened when a visitor taps WhatsApp"/> : <input type={field === "email" ? "email" : field.includes("url") || field === "instagram" || field === "facebook" || field === "linkedin" ? "url" : "text"} value={String(value ?? "")} onChange={(event) => edit(item.id, field, event.target.value)}/>}</label>)}</div><button className="button button-primary" disabled={saving === item.id} onClick={() => void save(item)}>{saving === item.id ? "Saving…" : "Save changes"}</button></article>; })}</section> : <EmptyState title="No settings available" text="Run the KODESK Supabase migrations to create public website settings."/>}</>;
}
