"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { supabase } from "../../../lib/supabase";
import type { Inquiry } from "../../../lib/types";
import { Icon } from "../../../components/admin/icons";
import { EmptyState, LoadingState, PageHeader, StatCard, StatusBadge } from "../../../components/admin/ui";

export default function DashboardPage() {
  const [items, setItems] = useState<Inquiry[]>([]); const [counts, setCounts] = useState({ total: 0, new: 0, contacted: 0, closed: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = async () => { if (!supabase) return; setLoading(true); setError(""); const [all, recent] = await Promise.all([supabase.from("enquiries").select("status"), supabase.from("enquiries").select("*").order("created_at", { ascending: false }).limit(6)]); if (all.error || recent.error) setError("We couldn't load workspace activity. Please try again."); const list = all.data ?? []; setCounts({ total: list.length, new: list.filter((item) => item.status === "new").length, contacted: list.filter((item) => item.status === "contacted").length, closed: list.filter((item) => item.status === "closed").length }); setItems((recent.data ?? []) as Inquiry[]); setLoading(false); };
  useEffect(() => { void load(); }, []);
  return <><PageHeader title="Dashboard" subtitle="Overview of your KODESK workspace activity" action={<button className="button button-secondary" onClick={() => void load()}><Icon name="refresh"/> Refresh</button>}/>{error && <div className="inline-error">{error}<button onClick={() => void load()}>Retry</button></div>}{loading ? <LoadingState rows={6}/> : <><section className="stats-grid"><StatCard label="Total enquiries" value={counts.total} icon="inbox"/><StatCard label="New enquiries" value={counts.new} icon="phone"/><StatCard label="Contacted" value={counts.contacted} icon="check"/><StatCard label="Closed" value={counts.closed} icon="check"/></section><section className="dashboard-grid"><article className="surface recent-panel"><div className="surface-heading"><div><h2>Recent enquiries</h2><p>Latest messages from the public website</p></div><Link className="text-link" href="/enquiries">View all <Icon name="arrow"/></Link></div>{items.length ? <div className="recent-list">{items.map((item) => <Link href="/enquiries" key={item.id} className="recent-item"><span className="initial">{item.name.slice(0, 1).toUpperCase()}</span><div><b>{item.name}</b><small>{item.interested_in || "General enquiry"}</small></div><StatusBadge status={item.status}/><time>{new Date(item.created_at).toLocaleDateString("en-IN", { day: "numeric", month: "short" })}</time></Link>)}</div> : <EmptyState title="No enquiries yet" text="New enquiries submitted through the KODESK website will appear here." action={<a className="button button-secondary" href={process.env.NEXT_PUBLIC_PUBLIC_WEBSITE_URL ?? "https://kodesk-coworking-space.vercel.app"} target="_blank" rel="noreferrer">View website</a>}/>}</article><aside className="surface quick-panel"><div className="surface-heading"><div><h2>Quick actions</h2><p>Common management tasks</p></div></div><div className="quick-actions"><Link href="/enquiries"><Icon name="inbox"/><span>View enquiries</span><Icon name="arrow"/></Link><Link href="/pricing"><Icon name="tag"/><span>Manage pricing</span><Icon name="arrow"/></Link><Link href="/media"><Icon name="image"/><span>Manage media</span><Icon name="arrow"/></Link><Link href="/settings"><Icon name="settings"/><span>Website settings</span><Icon name="arrow"/></Link></div></aside></section></>}</>;
}
