"use client";

import { useEffect, useState } from "react";
import { ConfirmDialog, EmptyState, LoadingState, PageHeader } from "../../../components/admin/ui";
import { supabase } from "../../../lib/supabase";
import type { LocalSeoPage, Service } from "../../../lib/types";

const blank = (): Omit<LocalSeoPage, "id"> => ({ slug: "", service_slug: "coworking-space", title: "", description: "", seo_title: "", seo_description: "", is_active: true, sort_order: 0 });

export default function LocalSeoPageManager() {
  const [pages, setPages] = useState<LocalSeoPage[]>([]); const [services, setServices] = useState<Service[]>([]); const [draft, setDraft] = useState<Omit<LocalSeoPage, "id"> | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [removeId, setRemoveId] = useState<string | null>(null); const [notice, setNotice] = useState("");
  const load = async () => { if (!supabase) return; setLoading(true); const [pageResult, serviceResult] = await Promise.all([supabase.from("local_seo_pages").select("*").order("sort_order"), supabase.from("services").select("*").order("sort_order")]); if (pageResult.error?.code === "42P01") setNotice("Apply migration 202608220008_local_seo_pages.sql to enable local SEO page management."); setPages((pageResult.data ?? []) as LocalSeoPage[]); setServices((serviceResult.data ?? []) as Service[]); setLoading(false); };
  useEffect(() => { void load(); }, []);
  const update = (id: string, value: Partial<LocalSeoPage>) => setPages((current) => current.map((page) => page.id === id ? { ...page, ...value } : page));
  const save = async (page: LocalSeoPage) => { if (!supabase || !page.slug || !page.title || !page.description) { setNotice("Slug, title and description are required."); return; } setSaving(true); const { error } = await supabase.from("local_seo_pages").update({ slug: page.slug, service_slug: page.service_slug, title: page.title, description: page.description, seo_title: page.seo_title || null, seo_description: page.seo_description || null, is_active: page.is_active, sort_order: page.sort_order }).eq("id", page.id); setSaving(false); setNotice(error ? "Unable to save the local SEO page." : "Local SEO page saved."); };
  const create = async () => { if (!supabase || !draft?.slug || !draft.title || !draft.description) { setNotice("Slug, title and description are required."); return; } setSaving(true); const { error } = await supabase.from("local_seo_pages").insert({ ...draft, seo_title: draft.seo_title || null, seo_description: draft.seo_description || null }); setSaving(false); if (error) { setNotice("Unable to create the local SEO page. Check that the slug is unique."); return; } setDraft(null); setNotice("Local SEO page created."); void load(); };
  const remove = async () => { if (!supabase || !removeId) return; setSaving(true); const { error } = await supabase.from("local_seo_pages").delete().eq("id", removeId); setSaving(false); setRemoveId(null); setNotice(error ? "Unable to delete this page." : "Local SEO page deleted."); if (!error) void load(); };
  const fields = (page: Omit<LocalSeoPage, "id">, onChange: (value: Partial<LocalSeoPage>) => void) => <div className="settings-fields"><label>URL slug<input value={page.slug} maxLength={100} placeholder="coworking-space-baner" onChange={(event) => onChange({ slug: event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "-") })} /></label><label>Service template<select value={page.service_slug} onChange={(event) => onChange({ service_slug: event.target.value })}>{services.map((service) => <option key={service.id} value={service.slug}>{service.name}</option>)}</select></label><label>Page title<input value={page.title} maxLength={160} onChange={(event) => onChange({ title: event.target.value })} /></label><label>Sort order<input type="number" value={page.sort_order} onChange={(event) => onChange({ sort_order: Number(event.target.value) || 0 })} /></label><label className="settings-full">Page description<textarea value={page.description} maxLength={500} onChange={(event) => onChange({ description: event.target.value })} /></label><label>SEO title <small>(optional)</small><input value={page.seo_title ?? ""} maxLength={160} onChange={(event) => onChange({ seo_title: event.target.value })} /></label><label>SEO description <small>(optional)</small><textarea value={page.seo_description ?? ""} maxLength={320} onChange={(event) => onChange({ seo_description: event.target.value })} /></label></div>;
  return <><PageHeader title="Local SEO" subtitle="Manage location and service landing pages using approved KODESK service templates." action={<button className="button button-primary" onClick={() => setDraft(blank())}>Add local page</button>} />{notice && <div className="toast-message">{notice}</div>}{loading ? <LoadingState rows={5} /> : <div className="editor-grid">{draft && <section className="surface editor-panel editor-wide"><div className="surface-heading"><div><p className="section-kicker">NEW LANDING PAGE</p><h2>Create local SEO page</h2></div></div>{fields(draft, (value) => setDraft({ ...draft, ...value }))}<div className="editor-actions"><button className="button button-secondary" onClick={() => setDraft(null)}>Cancel</button><button className="button button-primary" disabled={saving} onClick={() => void create()}>{saving ? "Creating…" : "Create page"}</button></div></section>}{pages.length ? pages.map((page) => <section className="surface editor-panel editor-wide" key={page.id}><div className="surface-heading"><div><p className="section-kicker">/{page.slug}</p><h2>{page.title}</h2></div><label className="switch"><input type="checkbox" checked={page.is_active} onChange={(event) => update(page.id, { is_active: event.target.checked })} /><span />Active</label></div>{fields(page, (value) => update(page.id, value))}<div className="editor-actions"><a className="button button-ghost" href={`${process.env.NEXT_PUBLIC_PUBLIC_WEBSITE_URL ?? "https://kodesk-coworking-space.vercel.app"}/${page.slug}`} target="_blank" rel="noreferrer">Preview page</a><button className="button button-danger" disabled={saving} onClick={() => setRemoveId(page.id)}>Delete</button><button className="button button-primary" disabled={saving} onClick={() => void save(page)}>{saving ? "Saving…" : "Save changes"}</button></div></section>) : !draft && <EmptyState title="No local SEO pages" text="Create a controlled location landing page, then manage its copy and visibility here." />}</div>}<ConfirmDialog open={Boolean(removeId)} title="Delete local SEO page?" text="This removes the page record. The public route will fall back only if it exists in the original static page list." onCancel={() => setRemoveId(null)} onConfirm={() => void remove()} /></>;
}
