"use client";

import { useEffect, useState } from "react";
import { EmptyState, LoadingState, PageHeader } from "../../../components/admin/ui";
import { supabase } from "../../../lib/supabase";

type Media = { id: string; name: string; public_url: string; category: string; alt_text: string | null; is_active: boolean };
type Detail = { cover_image_url: string | null; hero_image_url: string | null; gallery_image_urls: string[] | null };
export default function MediaAuditPage() { const [items, setItems] = useState<Array<Media & { references: number }>>([]); const [loading, setLoading] = useState(true); useEffect(() => { void (async () => { if (!supabase) return; const [mediaResult, detailsResult] = await Promise.all([supabase.from("media").select("id,name,public_url,category,alt_text,is_active").order("name"), supabase.from("service_page_details").select("cover_image_url,hero_image_url,gallery_image_urls")]); const details = (detailsResult.data ?? []) as Detail[]; setItems(((mediaResult.data ?? []) as Media[]).map((item) => ({ ...item, references: details.reduce((total, detail) => total + Number(detail.cover_image_url === item.public_url) + Number(detail.hero_image_url === item.public_url) + Number((detail.gallery_image_urls ?? []).includes(item.public_url)), 0) }))); setLoading(false); })(); }, []); const unused = items.filter((item) => item.references === 0 && item.category !== "gallery"); return <><PageHeader title="Media audit" subtitle="Review image accessibility and known service-page references before deciding whether media can be retired." />{loading ? <LoadingState rows={7} /> : <div className="editor-grid"><section className="surface editor-panel"><div className="surface-heading"><div><p className="section-kicker">REFERENCE REVIEW</p><h2>Potentially unused media</h2><p>Only service-page references are checked here. Gallery media may be public content even with zero service references.</p></div></div>{unused.length ? unused.map((item) => <div className="revision-item" key={item.id}><div><b>{item.name}</b><small>{item.category} · {item.is_active ? "Active" : "Hidden"} · no service references</small></div></div>) : <EmptyState title="No candidates found" text="All non-gallery media has at least one known service-page reference." />}</section><section className="surface editor-panel"><div className="surface-heading"><div><p className="section-kicker">ALL MEDIA</p><h2>Reference counts</h2><p>Counts cover cover images, service heroes and service galleries.</p></div></div>{items.map((item) => <div className="revision-item" key={item.id}><div><b>{item.name}</b><small>{item.references} known service reference{item.references === 1 ? "" : "s"}{!item.alt_text ? " · missing alt text" : ""}</small></div><span className={`editor-state ${item.references ? "published" : "draft"}`}>{item.references ? "Referenced" : "Review"}</span></div>)}</section></div>}</>; }
