"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../../../lib/supabase";
import { MediaPicker } from "../../../../components/admin/MediaPicker";
import { LoadingState, PageHeader } from "../../../../components/admin/ui";

type AboutHero = { title: string; description: string; primary_label: string; primary_url: string; secondary_label: string; secondary_url: string; image_url: string };
type DocumentRow = { draft_content: AboutHero; published_content: AboutHero; published_version: number };
const documentKey = "about.hero";
const fallback: AboutHero = { title: "About KODESK", description: "Flexible workspace solutions for professionals, startups and businesses in Baner, Pune.", primary_label: "Book a Tour", primary_url: "/contact", secondary_label: "View Pricing Plans", secondary_url: "/pricing", image_url: "" };
const normalize = (value: unknown): AboutHero => ({ ...fallback, ...(value && typeof value === "object" ? Object.fromEntries(Object.entries(value).filter(([, item]) => typeof item === "string")) : {}) });

export default function AboutHeroEditorPage() {
  const [draft, setDraft] = useState<AboutHero>(fallback); const [published, setPublished] = useState<AboutHero>(fallback); const [version, setVersion] = useState(0); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState("");
  const changed = useMemo(() => JSON.stringify(draft) !== JSON.stringify(published), [draft, published]);
  const load = async () => { if (!supabase) return; setLoading(true); const result = await supabase.from("content_documents").select("draft_content,published_content,published_version").eq("document_key", documentKey).maybeSingle(); if (result.error?.code === "42P01") { setNotice("Apply migration 202608220007_cms_publication_workflow.sql to enable drafts and publishing."); setLoading(false); return; } const row = result.data as DocumentRow | null; if (row) { setDraft(normalize(row.draft_content)); setPublished(row.published_version ? normalize(row.published_content) : fallback); setVersion(row.published_version); } setLoading(false); };
  useEffect(() => { void load(); }, []);
  const saveDraft = async () => { if (!supabase) return; setSaving(true); const { data: auth } = await supabase.auth.getUser(); const result = await supabase.from("content_documents").upsert({ document_key: documentKey, draft_content: draft, draft_updated_by: auth.user?.id ?? null }, { onConflict: "document_key" }); setSaving(false); setNotice(result.error ? "Unable to save the About hero draft." : "Draft saved. The public About page has not changed."); };
  const publish = async () => { if (!supabase || !draft.title.trim() || !draft.description.trim()) { setNotice("A title and description are required before publishing."); return; } setSaving(true); const { data: auth } = await supabase.auth.getUser(); const nextVersion = version + 1; const documentResult = await supabase.from("content_documents").upsert({ document_key: documentKey, draft_content: draft, published_content: draft, draft_updated_by: auth.user?.id ?? null, published_by: auth.user?.id ?? null, published_at: new Date().toISOString(), published_version: nextVersion }, { onConflict: "document_key" }); const revisionResult = documentResult.error ? { error: documentResult.error } : await supabase.from("content_revisions").insert({ document_key: documentKey, version: nextVersion, content: draft, action: "published", created_by: auth.user?.id ?? null }); setSaving(false); if (revisionResult.error) { setNotice("Publish could not be completed. The public About page remains unchanged."); return; } setPublished(draft); setVersion(nextVersion); setNotice("About hero published successfully."); };
  if (loading) return <LoadingState rows={6} />;
  return <><PageHeader title="About Page Hero" subtitle="Manage the existing About hero content and image without changing its premium layout." action={<Link className="button button-secondary" href="/editor">Back to Website Editor</Link>} />{notice && <div className="toast-message">{notice}</div>}<section className="surface editor-panel editor-wide"><div className="surface-heading"><div><p className="section-kicker">ABOUT · HERO</p><h2>Hero content</h2><p>Save a private draft first. Publish only when the page is ready for visitors.</p></div><span className={`editor-state ${changed ? "draft" : "published"}`}>{changed ? "Draft changes" : "Published"}</span></div><label>Page title<input maxLength={120} value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} /></label><label>Description<textarea maxLength={400} value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label><div className="settings-fields"><label>Primary button label<input maxLength={50} value={draft.primary_label} onChange={(event) => setDraft({ ...draft, primary_label: event.target.value })} /></label><label>Primary button URL<input value={draft.primary_url} onChange={(event) => setDraft({ ...draft, primary_url: event.target.value })} /></label><label>Secondary button label<input maxLength={50} value={draft.secondary_label} onChange={(event) => setDraft({ ...draft, secondary_label: event.target.value })} /></label><label>Secondary button URL<input value={draft.secondary_url} onChange={(event) => setDraft({ ...draft, secondary_url: event.target.value })} /></label></div><MediaPicker label="Hero image" value={draft.image_url || null} onChange={(value) => setDraft({ ...draft, image_url: typeof value === "string" ? value : "" })} /><div className="editor-actions"><button className="button button-secondary" type="button" disabled={saving} onClick={() => void saveDraft()}>{saving ? "Saving…" : "Save Draft"}</button><button className="button button-primary" type="button" disabled={saving} onClick={() => void publish()}>{saving ? "Publishing…" : "Publish About hero"}</button></div></section></>;
}
