"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../../../lib/supabase";
import { LoadingState, PageHeader } from "../../../../components/admin/ui";

type Testimonial = { name: string; role: string; rating: number; quote: string; is_active: boolean; sort_order: number };
type Row = { draft_content: { heading?: string; description?: string; items?: Testimonial[] }; published_content: { heading?: string; description?: string; items?: Testimonial[] }; published_version: number };
const fallback = { heading: "What Our Members Say", description: "Hear from professionals and businesses working from KODESK.", items: [] as Testimonial[] };
const normalize = (value: unknown) => { const source = value && typeof value === "object" ? value as Partial<typeof fallback> : {}; return { heading: typeof source.heading === "string" ? source.heading : fallback.heading, description: typeof source.description === "string" ? source.description : fallback.description, items: Array.isArray(source.items) ? source.items.filter((item): item is Testimonial => Boolean(item && typeof item.name === "string" && typeof item.role === "string" && typeof item.quote === "string")).map((item, index) => ({ ...item, rating: Math.min(5, Math.max(1, Number(item.rating) || 5)), is_active: item.is_active !== false, sort_order: Number(item.sort_order) || index + 1 })) : [] }; };

export default function HomeTestimonialsEditorPage() {
  const [draft, setDraft] = useState(fallback); const [published, setPublished] = useState(fallback); const [version, setVersion] = useState(0); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(""); const changed = useMemo(() => JSON.stringify(draft) !== JSON.stringify(published), [draft, published]);
  const load = async () => { if (!supabase) return; const result = await supabase.from("content_documents").select("draft_content,published_content,published_version").eq("document_key", "home.testimonials").maybeSingle(); if (result.error?.code === "42P01") setNotice("Apply migration 202608220007_cms_publication_workflow.sql to enable publishing."); const row = result.data as Row | null; if (row) { setDraft(normalize(row.draft_content)); setPublished(row.published_version ? normalize(row.published_content) : fallback); setVersion(row.published_version); } setLoading(false); };
  useEffect(() => { void load(); }, []);
  const updateItem = (index: number, value: Partial<Testimonial>) => setDraft((current) => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, ...value } : item) }));
  const save = async (publish: boolean) => { if (!supabase || (publish && draft.items.some((item) => !item.name.trim() || !item.role.trim() || !item.quote.trim()))) { setNotice("Every testimonial needs a name, role and quote before publishing."); return; } setSaving(true); const { data: auth } = await supabase.auth.getUser(); const next = version + 1; const result = publish ? await supabase.from("content_documents").upsert({ document_key: "home.testimonials", draft_content: draft, published_content: draft, draft_updated_by: auth.user?.id ?? null, published_by: auth.user?.id ?? null, published_at: new Date().toISOString(), published_version: next }, { onConflict: "document_key" }) : await supabase.from("content_documents").upsert({ document_key: "home.testimonials", draft_content: draft, draft_updated_by: auth.user?.id ?? null }, { onConflict: "document_key" }); const revision = !publish || result.error ? { error: result.error } : await supabase.from("content_revisions").insert({ document_key: "home.testimonials", version: next, content: draft, action: "published", created_by: auth.user?.id ?? null }); setSaving(false); if (revision.error) { setNotice("Unable to save testimonials."); return; } if (publish) { setPublished(draft); setVersion(next); setNotice("Testimonials published."); } else setNotice("Draft saved. Public site unchanged."); };
  if (loading) return <LoadingState rows={5} />;
  return <><PageHeader title="Homepage testimonials" subtitle="Publish only verified member feedback. The existing testimonial design remains protected." action={<Link className="button button-secondary" href="/editor">Back to Website Editor</Link>} />{notice && <div className="toast-message">{notice}</div>}<section className="surface editor-panel editor-wide"><div className="surface-heading"><div><p className="section-kicker">HOME · TESTIMONIALS</p><h2>Member feedback</h2></div><span className={`editor-state ${changed ? "draft" : "published"}`}>{changed ? "Draft changes" : "Published"}</span></div><div className="settings-fields"><label>Heading<input maxLength={100} value={draft.heading} onChange={(event) => setDraft({ ...draft, heading: event.target.value })} /></label><label>Description<input maxLength={220} value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} /></label></div><div className="faq-editor-list">{draft.items.map((item, index) => <article className="faq-editor-item" key={`${item.name}-${index}`}><div className="faq-editor-title"><b>Testimonial {index + 1}</b><button className="button button-danger" onClick={() => setDraft({ ...draft, items: draft.items.filter((_, itemIndex) => itemIndex !== index) })}>Remove</button></div><div className="settings-fields"><label>Name<input maxLength={80} value={item.name} onChange={(event) => updateItem(index, { name: event.target.value })} /></label><label>Role<input maxLength={100} value={item.role} onChange={(event) => updateItem(index, { role: event.target.value })} /></label><label>Rating<select value={item.rating} onChange={(event) => updateItem(index, { rating: Number(event.target.value) })}>{[5,4,3,2,1].map((rating) => <option key={rating} value={rating}>{rating} stars</option>)}</select></label><label className="switch service-active"><input type="checkbox" checked={item.is_active} onChange={(event) => updateItem(index, { is_active: event.target.checked })} /><span />Visible</label></div><label>Quote<textarea maxLength={700} value={item.quote} onChange={(event) => updateItem(index, { quote: event.target.value })} /></label></article>)}</div><button className="button button-ghost" onClick={() => setDraft({ ...draft, items: [...draft.items, { name: "", role: "", rating: 5, quote: "", is_active: true, sort_order: draft.items.length + 1 }] })}>Add testimonial</button><div className="editor-actions"><button className="button button-secondary" disabled={saving} onClick={() => void save(false)}>Save Draft</button><button className="button button-primary" disabled={saving} onClick={() => void save(true)}>Publish testimonials</button></div></section></>;
}
