"use client";

import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { supabase } from "../../lib/supabase";
import type { Media } from "../../lib/types";

const accepted = ["image/jpeg", "image/png", "image/webp"];
const maxImageBytes = 5 * 1024 * 1024;

export function MediaPicker({ label, value, onChange, multiple = false }: { label: string; value: string | string[] | null; onChange: (value: string | string[] | null) => void; multiple?: boolean }) {
  const [items, setItems] = useState<Media[]>([]); const [query, setQuery] = useState(""); const [open, setOpen] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState("");
  const selected = useMemo(() => Array.isArray(value) ? value : value ? [value] : [], [value]);
  const filtered = useMemo(() => items.filter((item) => `${item.name} ${item.alt_text ?? ""}`.toLowerCase().includes(query.toLowerCase())), [items, query]);
  useEffect(() => { if (!supabase || !open) return; void (async () => { const { data } = await supabase.from("media").select("*").eq("is_active", true).order("sort_order"); setItems((data ?? []) as Media[]); })(); }, [open]);
  const select = (url: string) => { if (!multiple) { onChange(url); setOpen(false); return; } onChange(selected.includes(url) ? selected.filter((item) => item !== url) : [...selected, url]); };
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files ?? []); if (!supabase || !files.length) return; const invalid = files.find((file) => !accepted.includes(file.type) || file.size > maxImageBytes); if (invalid) { setError("Use JPEG, PNG or WebP images under 5 MB."); return; } setUploading(true); setError(""); const added: Media[] = []; for (const file of files) { const storage_path = `service/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`; const uploaded = await supabase.storage.from("kodesk-media").upload(storage_path, file, { contentType: file.type, upsert: false }); if (uploaded.error) continue; const public_url = supabase.storage.from("kodesk-media").getPublicUrl(storage_path).data.publicUrl; const inserted = await supabase.from("media").insert({ name: file.name, storage_path, public_url, category: "service", is_active: true, sort_order: items.length + added.length + 1 }).select().single(); if (inserted.data) added.push(inserted.data as Media); }
    setItems((current) => [...added, ...current]); if (added.length) { const urls = added.map((item) => item.public_url); onChange(multiple ? [...selected, ...urls] : urls[0]); } if (added.length !== files.length) setError(`${added.length} of ${files.length} images uploaded.`); setUploading(false); event.target.value = ""; };
  const move = (url: string, direction: -1 | 1) => { const index = selected.indexOf(url); const target = index + direction; if (target < 0 || target >= selected.length) return; const reordered = [...selected]; [reordered[index], reordered[target]] = [reordered[target], reordered[index]]; onChange(reordered); };
  return <div className="media-picker"><div className="media-picker-heading"><span>{label}</span><button type="button" className="button button-secondary" onClick={() => setOpen(true)}>Choose image{multiple ? "s" : ""}</button></div>{selected.length ? <div className="media-picker-selection">{selected.map((url, index) => <div key={url}><img src={url} alt="Selected media"/>{multiple ? <div className="media-picker-order"><button type="button" disabled={index === 0} onClick={() => move(url, -1)}>←</button><button type="button" disabled={index === selected.length - 1} onClick={() => move(url, 1)}>→</button></div> : null}<button type="button" onClick={() => onChange(multiple ? selected.filter((item) => item !== url) : null)}>Remove</button></div>)}</div> : <p className="field-help">No image selected. The existing public fallback will remain in use.</p>}{open ? <div className="dialog-backdrop" onMouseDown={() => setOpen(false)}><section className="media-picker-dialog" role="dialog" aria-modal="true" aria-label={`Choose ${label}`} onMouseDown={(event) => event.stopPropagation()}><div className="surface-heading"><div><p className="section-kicker">MEDIA LIBRARY</p><h2>{label}</h2><p>Choose existing media or upload new files.</p></div><button type="button" className="icon-button" onClick={() => setOpen(false)}>×</button></div><div className="media-picker-toolbar"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search images…"/><label className="button button-primary file-button">{uploading ? "Uploading…" : "Upload image"}{multiple ? "s" : ""}<input type="file" multiple={multiple} accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={(event) => void upload(event)}/></label></div>{error && <div className="inline-error">{error}</div>}<div className="media-picker-grid">{filtered.map((item) => <button type="button" key={item.id} onClick={() => select(item.public_url)} className={selected.includes(item.public_url) ? "selected" : ""}><img src={item.public_url} alt={item.alt_text || item.name}/><span>{item.name}</span></button>)}</div>{multiple && <div className="dialog-actions"><button type="button" className="button button-primary" onClick={() => setOpen(false)}>Use selected images</button></div>}</section></div> : null}</div>;
}
