"use client";
import { useEffect } from "react";
import { Icon } from "./icons";

export function PageHeader({ title, subtitle, action }: { title: string; subtitle: string; action?: React.ReactNode }) { return <div className="page-header"><div><p className="section-kicker">KODESK MANAGEMENT</p><h1>{title}</h1><p>{subtitle}</p></div>{action}</div>; }
export function StatusBadge({ status }: { status: "new" | "contacted" | "closed" | string }) { return <span className={`status status-${status}`}>{status === "new" ? "New" : status === "contacted" ? "Contacted" : status === "closed" ? "Closed" : status}</span>; }
export function StatCard({ label, value, icon }: { label: string; value: number; icon: "inbox" | "check" | "phone" }) { return <article className="stat-card"><span className="stat-icon"><Icon name={icon}/></span><div><strong>{value}</strong><span>{label}</span></div></article>; }
export function EmptyState({ title, text, action }: { title: string; text: string; action?: React.ReactNode }) { return <div className="empty-state"><span className="empty-mark">K</span><h3>{title}</h3><p>{text}</p>{action}</div>; }
export function LoadingState({ rows = 4 }: { rows?: number }) { return <div className="skeleton-stack" aria-label="Loading content">{Array.from({ length: rows }, (_, index) => <span key={index} className="skeleton" />)}</div>; }
export function ConfirmDialog({ open, title, text, confirmLabel = "Delete", onCancel, onConfirm }: { open: boolean; title: string; text: string; confirmLabel?: string; onCancel: () => void; onConfirm: () => void }) { useEffect(() => { if (!open) return; const close = (event: KeyboardEvent) => event.key === "Escape" && onCancel(); document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, [open, onCancel]); if (!open) return null; return <div className="dialog-backdrop" role="presentation" onMouseDown={onCancel}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title" onMouseDown={(event) => event.stopPropagation()}><h2 id="dialog-title">{title}</h2><p>{text}</p><div className="dialog-actions"><button className="button button-secondary" onClick={onCancel}>Cancel</button><button className="button button-danger" onClick={onConfirm}>{confirmLabel}</button></div></section></div>; }
