"use client";

import { useEffect, useState } from "react";
import { LoadingState, PageHeader } from "../../../components/admin/ui";
import { supabase } from "../../../lib/supabase";

type Section = { id: string; page_key: string; section_key: string; is_visible: boolean; sort_order: number };
const approved = [
  ["home", "testimonials", "Member testimonials"], ["home", "faq", "Frequently asked questions"],
  ["about", "mission", "Mission and vision"], ["about", "stats", "Statistics"], ["about", "values", "Core values"], ["about", "community", "Community section"], ["about", "cta", "Closing CTA"],
  ["contact", "support", "Support and tour section"], ["contact", "faq", "Contact FAQs"],
] as const;

export default function SectionsPage() { const [items, setItems] = useState<Section[]>([]); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [notice, setNotice] = useState(""); const load = async () => { if (!supabase) return; const result = await supabase.from("cms_section_settings").select("*").order("page_key").order("sort_order"); if (result.error) setNotice("Unable to load section settings."); setItems((result.data ?? []) as Section[]); setLoading(false); }; useEffect(() => { void load(); }, []); const get = (page: string, section: string) => items.find((item) => item.page_key === page && item.section_key === section); const save = async (page_key: string, section_key: string, values: Partial<Section>) => { if (!supabase) return; setSaving(true); const current = get(page_key, section_key); const result = await supabase.from("cms_section_settings").upsert({ page_key, section_key, is_visible: values.is_visible ?? current?.is_visible ?? true, sort_order: values.sort_order ?? current?.sort_order ?? approved.findIndex(([page, section]) => page === page_key && section === section_key) + 1 }, { onConflict: "page_key,section_key" }); setSaving(false); setNotice(result.error ? "Unable to save section settings." : "Section setting saved."); if (!result.error) void load(); }; const move = async (index: number, direction: -1 | 1) => { const target = index + direction; if (target < 0 || target >= approved.length) return; const current = approved[index]; const next = approved[target]; const currentItem = get(current[0], current[1]); const nextItem = get(next[0], next[1]); await Promise.all([save(current[0], current[1], { sort_order: nextItem?.sort_order ?? target + 1 }), save(next[0], next[1], { sort_order: currentItem?.sort_order ?? index + 1 })]); }; return <><PageHeader title="Section controls" subtitle="Show or hide only developer-approved public sections. Page structure and responsive behavior stay protected." />{notice && <div className="toast-message">{notice}</div>}{loading ? <LoadingState rows={8} /> : <section className="surface editor-panel editor-wide"><div className="revision-list">{approved.map(([page, section, label], index) => { const item = get(page, section); return <div className="revision-item" key={`${page}-${section}`}><div><b>{label}</b><small>{page} page · order {item?.sort_order ?? index + 1}</small></div><div className="editor-actions"><button className="button button-ghost" disabled={saving || index === 0} onClick={() => void move(index, -1)}>↑</button><button className="button button-ghost" disabled={saving || index === approved.length - 1} onClick={() => void move(index, 1)}>↓</button><label className="switch service-active"><input type="checkbox" checked={item?.is_visible ?? true} disabled={saving} onChange={(event) => void save(page, section, { is_visible: event.target.checked })} /><span />Visible</label></div></div>; })}</div></section>}</>; }
