"use client";

import { useEffect, useState } from "react";
import { EmptyState, LoadingState, PageHeader } from "../../../components/admin/ui";
import { supabase } from "../../../lib/supabase";

type MediaIssue = { id: string; name: string; public_url: string; alt_text: string | null };
type ServiceIssue = { slug: string; name: string; seo_title: string | null; seo_description: string | null; issue: string };
export default function QualityPage() { const [media, setMedia] = useState<MediaIssue[]>([]); const [services, setServices] = useState<ServiceIssue[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { void (async () => { if (!supabase) return; const [mediaResult, serviceResult] = await Promise.all([supabase.from("media").select("id,name,public_url,alt_text").or("alt_text.is.null,alt_text.eq."), supabase.from("service_page_details").select("service_slug,seo_title,seo_description,services(name)")]); setMedia((mediaResult.data ?? []) as MediaIssue[]); const rows = (serviceResult.data ?? []) as { service_slug: string; seo_title: string | null; seo_description: string | null; services?: { name?: string }[] | null }[]; const titles = new Map<string, number>(); rows.forEach((item) => { if (item.seo_title) titles.set(item.seo_title, (titles.get(item.seo_title) ?? 0) + 1); }); setServices(rows.flatMap((item) => { const issues: string[] = []; if (!item.seo_title) issues.push("Missing title"); else if (item.seo_title.length < 30 || item.seo_title.length > 60) issues.push(`Title length ${item.seo_title.length} (recommended 30–60)`); if (!item.seo_description) issues.push("Missing description"); else if (item.seo_description.length < 70 || item.seo_description.length > 160) issues.push(`Description length ${item.seo_description.length} (recommended 70–160)`); if (item.seo_title && (titles.get(item.seo_title) ?? 0) > 1) issues.push("Duplicate title"); return issues.length ? [{ slug: item.service_slug, name: item.services?.[0]?.name ?? item.service_slug, seo_title: item.seo_title, seo_description: item.seo_description, issue: issues.join(" · ") }] : []; })); setLoading(false); })(); }, []); return <><PageHeader title="Content quality" subtitle="Review high-impact SEO and accessibility gaps before publishing." />{loading ? <LoadingState rows={6} /> : <div className="editor-grid"><section className="surface editor-panel"><div className="surface-heading"><div><p className="section-kicker">MEDIA</p><h2>Missing alt text</h2><p>Images without descriptive alt text should be updated in Media.</p></div></div>{media.length ? media.map((item) => <div className="revision-item" key={item.id}><div><b>{item.name}</b><small>Missing alt text</small></div></div>) : <EmptyState title="No missing alt text" text="All queried media has descriptive alt text." />}</section><section className="surface editor-panel"><div className="surface-heading"><div><p className="section-kicker">SERVICE SEO</p><h2>Metadata quality</h2><p>Recommended lengths: title 30–60 characters, description 70–160 characters.</p></div></div>{services.length ? services.map((item) => <div className="revision-item" key={item.slug}><div><b>{item.name}</b><small>{item.issue}</small></div></div>) : <EmptyState title="Service metadata healthy" text="All queried service pages meet the current metadata checks." />}</section></div>}</>; }
